INSERT INTO DEPARTMENT (NAME, LOCATION) values ('IT', 'abc 123');
INSERT INTO DEPARTMENT (NAME, LOCATION) values ('DEV', 'def 567');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, AGE, DEPARTMENT_ID) values ('John', 'Smith', 20, 1);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, AGE, DEPARTMENT_ID) values ('Kate', 'Williams', 22, 1);