CREATE TABLE DEPARTMENT (
    ID BIGINT IDENTITY PRIMARY KEY,  
    NAME VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(50) NOT NULL,
	CONSTRAINT IDX_DEPARTMENT_ID PRIMARY KEY (ID)
);

CREATE TABLE INSURANCE_POLICY (
    ID BIGINT IDENTITY PRIMARY KEY,  
    ISSURER VARCHAR(50) NOT NULL,
    POLICY_NUMBER VARCHAR(50) NOT NULL,
    VALID CHAR DEFAULT '1' NOT NULL,
	CONSTRAINT IDX_INSURANCE_POLICY_ID PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE (
    ID BIGINT IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    INSURANCE_POLICY_ID BIGINT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID) ON DELETE CASCADE,
    FOREIGN KEY (INSURANCE_POLICY_ID) REFERENCES INSURANCE_POLICY (ID),
	CONSTRAINT IDX_EMPLOYEE_ID PRIMARY KEY (ID)
);
