/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 * HL
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Profile.as).
 */
 
package training.hl.bean {

 
    [Bindable]
    public class ProfileBase {
 
    public function ProfileBase() {}
 

        private var _bio:String;
        private var _hobbies:String;
        private var _homePage:String;

        public function set bio(value:String):void {
            _bio = value;
        }
        public function get bio():String {
            return _bio;
        }

        public function set hobbies(value:String):void {
            _hobbies = value;
        }
        public function get hobbies():String {
            return _hobbies;
        }

        public function set homePage(value:String):void {
            _homePage = value;
        }
        public function get homePage():String {
            return _homePage;
        }
    }
}