/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package training.hl.bean {

    [Bindable]
    [RemoteClass(alias="training.hl.bean.Role")]
    public class Role extends RoleBase {
    }
}