/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 * HL
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RootEntity.as).
 */
 
package training.hl.bean {

 
    [Bindable]
    public class RootEntityBase {
 
    public function RootEntityBase() {}
 

    }
}